// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DBExcute.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DBExcute_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DBExcute_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DBExcute_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DBExcute_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DBExcute_2eproto;
class DBExeSqlReq;
class DBExeSqlReqDefaultTypeInternal;
extern DBExeSqlReqDefaultTypeInternal _DBExeSqlReq_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::DBExeSqlReq* Arena::CreateMaybeMessage<::DBExeSqlReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class DBExeSqlReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DBExeSqlReq) */ {
 public:
  inline DBExeSqlReq() : DBExeSqlReq(nullptr) {};
  virtual ~DBExeSqlReq();

  DBExeSqlReq(const DBExeSqlReq& from);
  DBExeSqlReq(DBExeSqlReq&& from) noexcept
    : DBExeSqlReq() {
    *this = ::std::move(from);
  }

  inline DBExeSqlReq& operator=(const DBExeSqlReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline DBExeSqlReq& operator=(DBExeSqlReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const DBExeSqlReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DBExeSqlReq* internal_default_instance() {
    return reinterpret_cast<const DBExeSqlReq*>(
               &_DBExeSqlReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DBExeSqlReq& a, DBExeSqlReq& b) {
    a.Swap(&b);
  }
  inline void Swap(DBExeSqlReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DBExeSqlReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DBExeSqlReq* New() const final {
    return CreateMaybeMessage<DBExeSqlReq>(nullptr);
  }

  DBExeSqlReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DBExeSqlReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const DBExeSqlReq& from);
  void MergeFrom(const DBExeSqlReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DBExeSqlReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DBExeSqlReq";
  }
  protected:
  explicit DBExeSqlReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_DBExcute_2eproto);
    return ::descriptor_table_DBExcute_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSqlcmdFieldNumber = 2,
    kExectypeFieldNumber = 1,
  };
  // string sqlcmd = 2;
  void clear_sqlcmd();
  const std::string& sqlcmd() const;
  void set_sqlcmd(const std::string& value);
  void set_sqlcmd(std::string&& value);
  void set_sqlcmd(const char* value);
  void set_sqlcmd(const char* value, size_t size);
  std::string* mutable_sqlcmd();
  std::string* release_sqlcmd();
  void set_allocated_sqlcmd(std::string* sqlcmd);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_sqlcmd();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_sqlcmd(
      std::string* sqlcmd);
  private:
  const std::string& _internal_sqlcmd() const;
  void _internal_set_sqlcmd(const std::string& value);
  std::string* _internal_mutable_sqlcmd();
  public:

  // uint32 exectype = 1;
  void clear_exectype();
  ::PROTOBUF_NAMESPACE_ID::uint32 exectype() const;
  void set_exectype(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_exectype() const;
  void _internal_set_exectype(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:DBExeSqlReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sqlcmd_;
  ::PROTOBUF_NAMESPACE_ID::uint32 exectype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_DBExcute_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DBExeSqlReq

// uint32 exectype = 1;
inline void DBExeSqlReq::clear_exectype() {
  exectype_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DBExeSqlReq::_internal_exectype() const {
  return exectype_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DBExeSqlReq::exectype() const {
  // @@protoc_insertion_point(field_get:DBExeSqlReq.exectype)
  return _internal_exectype();
}
inline void DBExeSqlReq::_internal_set_exectype(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  exectype_ = value;
}
inline void DBExeSqlReq::set_exectype(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_exectype(value);
  // @@protoc_insertion_point(field_set:DBExeSqlReq.exectype)
}

// string sqlcmd = 2;
inline void DBExeSqlReq::clear_sqlcmd() {
  sqlcmd_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& DBExeSqlReq::sqlcmd() const {
  // @@protoc_insertion_point(field_get:DBExeSqlReq.sqlcmd)
  return _internal_sqlcmd();
}
inline void DBExeSqlReq::set_sqlcmd(const std::string& value) {
  _internal_set_sqlcmd(value);
  // @@protoc_insertion_point(field_set:DBExeSqlReq.sqlcmd)
}
inline std::string* DBExeSqlReq::mutable_sqlcmd() {
  // @@protoc_insertion_point(field_mutable:DBExeSqlReq.sqlcmd)
  return _internal_mutable_sqlcmd();
}
inline const std::string& DBExeSqlReq::_internal_sqlcmd() const {
  return sqlcmd_.Get();
}
inline void DBExeSqlReq::_internal_set_sqlcmd(const std::string& value) {
  
  sqlcmd_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void DBExeSqlReq::set_sqlcmd(std::string&& value) {
  
  sqlcmd_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:DBExeSqlReq.sqlcmd)
}
inline void DBExeSqlReq::set_sqlcmd(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sqlcmd_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:DBExeSqlReq.sqlcmd)
}
inline void DBExeSqlReq::set_sqlcmd(const char* value,
    size_t size) {
  
  sqlcmd_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:DBExeSqlReq.sqlcmd)
}
inline std::string* DBExeSqlReq::_internal_mutable_sqlcmd() {
  
  return sqlcmd_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* DBExeSqlReq::release_sqlcmd() {
  // @@protoc_insertion_point(field_release:DBExeSqlReq.sqlcmd)
  return sqlcmd_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void DBExeSqlReq::set_allocated_sqlcmd(std::string* sqlcmd) {
  if (sqlcmd != nullptr) {
    
  } else {
    
  }
  sqlcmd_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sqlcmd,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:DBExeSqlReq.sqlcmd)
}
inline std::string* DBExeSqlReq::unsafe_arena_release_sqlcmd() {
  // @@protoc_insertion_point(field_unsafe_arena_release:DBExeSqlReq.sqlcmd)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return sqlcmd_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void DBExeSqlReq::unsafe_arena_set_allocated_sqlcmd(
    std::string* sqlcmd) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (sqlcmd != nullptr) {
    
  } else {
    
  }
  sqlcmd_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      sqlcmd, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:DBExeSqlReq.sqlcmd)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DBExcute_2eproto
