// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DBExcute.proto

#include "DBExcute.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
class DBExeSqlReqDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<DBExeSqlReq> _instance;
} _DBExeSqlReq_default_instance_;
static void InitDefaultsscc_info_DBExeSqlReq_DBExcute_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_DBExeSqlReq_default_instance_;
    new (ptr) ::DBExeSqlReq();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DBExeSqlReq::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DBExeSqlReq_DBExcute_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_DBExeSqlReq_DBExcute_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_DBExcute_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_DBExcute_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_DBExcute_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_DBExcute_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DBExeSqlReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::DBExeSqlReq, exectype_),
  PROTOBUF_FIELD_OFFSET(::DBExeSqlReq, sqlcmd_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::DBExeSqlReq)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_DBExeSqlReq_default_instance_),
};

const char descriptor_table_protodef_DBExcute_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016DBExcute.proto\"/\n\013DBExeSqlReq\022\020\n\010exect"
  "ype\030\001 \001(\r\022\016\n\006sqlcmd\030\002 \001(\tb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_DBExcute_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_DBExcute_2eproto_sccs[1] = {
  &scc_info_DBExeSqlReq_DBExcute_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_DBExcute_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DBExcute_2eproto = {
  false, false, descriptor_table_protodef_DBExcute_2eproto, "DBExcute.proto", 73,
  &descriptor_table_DBExcute_2eproto_once, descriptor_table_DBExcute_2eproto_sccs, descriptor_table_DBExcute_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_DBExcute_2eproto::offsets,
  file_level_metadata_DBExcute_2eproto, 1, file_level_enum_descriptors_DBExcute_2eproto, file_level_service_descriptors_DBExcute_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_DBExcute_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_DBExcute_2eproto)), true);

// ===================================================================

void DBExeSqlReq::InitAsDefaultInstance() {
}
class DBExeSqlReq::_Internal {
 public:
};

DBExeSqlReq::DBExeSqlReq(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:DBExeSqlReq)
}
DBExeSqlReq::DBExeSqlReq(const DBExeSqlReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  sqlcmd_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sqlcmd().empty()) {
    sqlcmd_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_sqlcmd(),
      GetArena());
  }
  exectype_ = from.exectype_;
  // @@protoc_insertion_point(copy_constructor:DBExeSqlReq)
}

void DBExeSqlReq::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_DBExeSqlReq_DBExcute_2eproto.base);
  sqlcmd_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  exectype_ = 0u;
}

DBExeSqlReq::~DBExeSqlReq() {
  // @@protoc_insertion_point(destructor:DBExeSqlReq)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void DBExeSqlReq::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  sqlcmd_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void DBExeSqlReq::ArenaDtor(void* object) {
  DBExeSqlReq* _this = reinterpret_cast< DBExeSqlReq* >(object);
  (void)_this;
}
void DBExeSqlReq::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DBExeSqlReq::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DBExeSqlReq& DBExeSqlReq::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_DBExeSqlReq_DBExcute_2eproto.base);
  return *internal_default_instance();
}


void DBExeSqlReq::Clear() {
// @@protoc_insertion_point(message_clear_start:DBExeSqlReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sqlcmd_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  exectype_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DBExeSqlReq::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 exectype = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          exectype_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string sqlcmd = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_sqlcmd();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "DBExeSqlReq.sqlcmd"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DBExeSqlReq::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DBExeSqlReq)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 exectype = 1;
  if (this->exectype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_exectype(), target);
  }

  // string sqlcmd = 2;
  if (this->sqlcmd().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sqlcmd().data(), static_cast<int>(this->_internal_sqlcmd().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DBExeSqlReq.sqlcmd");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sqlcmd(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DBExeSqlReq)
  return target;
}

size_t DBExeSqlReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DBExeSqlReq)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string sqlcmd = 2;
  if (this->sqlcmd().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sqlcmd());
  }

  // uint32 exectype = 1;
  if (this->exectype() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_exectype());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DBExeSqlReq::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DBExeSqlReq)
  GOOGLE_DCHECK_NE(&from, this);
  const DBExeSqlReq* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<DBExeSqlReq>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DBExeSqlReq)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DBExeSqlReq)
    MergeFrom(*source);
  }
}

void DBExeSqlReq::MergeFrom(const DBExeSqlReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DBExeSqlReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sqlcmd().size() > 0) {
    _internal_set_sqlcmd(from._internal_sqlcmd());
  }
  if (from.exectype() != 0) {
    _internal_set_exectype(from._internal_exectype());
  }
}

void DBExeSqlReq::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DBExeSqlReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DBExeSqlReq::CopyFrom(const DBExeSqlReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DBExeSqlReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DBExeSqlReq::IsInitialized() const {
  return true;
}

void DBExeSqlReq::InternalSwap(DBExeSqlReq* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  sqlcmd_.Swap(&other->sqlcmd_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(exectype_, other->exectype_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DBExeSqlReq::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::DBExeSqlReq* Arena::CreateMaybeMessage< ::DBExeSqlReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DBExeSqlReq >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
