// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Login_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Login_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Login_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Login_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[9]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Login_2eproto;
class AccountLoginAck;
class AccountLoginAckDefaultTypeInternal;
extern AccountLoginAckDefaultTypeInternal _AccountLoginAck_default_instance_;
class AccountLoginReq;
class AccountLoginReqDefaultTypeInternal;
extern AccountLoginReqDefaultTypeInternal _AccountLoginReq_default_instance_;
class AccountRegisterAck;
class AccountRegisterAckDefaultTypeInternal;
extern AccountRegisterAckDefaultTypeInternal _AccountRegisterAck_default_instance_;
class AccountRegisterReq;
class AccountRegisterReqDefaultTypeInternal;
extern AccountRegisterReqDefaultTypeInternal _AccountRegisterReq_default_instance_;
class LoadLogicSvrReq;
class LoadLogicSvrReqDefaultTypeInternal;
extern LoadLogicSvrReqDefaultTypeInternal _LoadLogicSvrReq_default_instance_;
class LogonPack;
class LogonPackDefaultTypeInternal;
extern LogonPackDefaultTypeInternal _LogonPack_default_instance_;
class MainPack;
class MainPackDefaultTypeInternal;
extern MainPackDefaultTypeInternal _MainPack_default_instance_;
class SelectEnterLogicSvrAck;
class SelectEnterLogicSvrAckDefaultTypeInternal;
extern SelectEnterLogicSvrAckDefaultTypeInternal _SelectEnterLogicSvrAck_default_instance_;
class SelectEnterLogicSvrReq;
class SelectEnterLogicSvrReqDefaultTypeInternal;
extern SelectEnterLogicSvrReqDefaultTypeInternal _SelectEnterLogicSvrReq_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::AccountLoginAck* Arena::CreateMaybeMessage<::AccountLoginAck>(Arena*);
template<> ::AccountLoginReq* Arena::CreateMaybeMessage<::AccountLoginReq>(Arena*);
template<> ::AccountRegisterAck* Arena::CreateMaybeMessage<::AccountRegisterAck>(Arena*);
template<> ::AccountRegisterReq* Arena::CreateMaybeMessage<::AccountRegisterReq>(Arena*);
template<> ::LoadLogicSvrReq* Arena::CreateMaybeMessage<::LoadLogicSvrReq>(Arena*);
template<> ::LogonPack* Arena::CreateMaybeMessage<::LogonPack>(Arena*);
template<> ::MainPack* Arena::CreateMaybeMessage<::MainPack>(Arena*);
template<> ::SelectEnterLogicSvrAck* Arena::CreateMaybeMessage<::SelectEnterLogicSvrAck>(Arena*);
template<> ::SelectEnterLogicSvrReq* Arena::CreateMaybeMessage<::SelectEnterLogicSvrReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum RequestCode : int {
  RequestNone = 0,
  User = 1,
  RequestCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  RequestCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool RequestCode_IsValid(int value);
constexpr RequestCode RequestCode_MIN = RequestNone;
constexpr RequestCode RequestCode_MAX = User;
constexpr int RequestCode_ARRAYSIZE = RequestCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RequestCode_descriptor();
template<typename T>
inline const std::string& RequestCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RequestCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RequestCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RequestCode_descriptor(), enum_t_value);
}
inline bool RequestCode_Parse(
    const std::string& name, RequestCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RequestCode>(
    RequestCode_descriptor(), name, value);
}
enum ActionCode : int {
  ActionNone = 0,
  Logon = 1,
  Login = 2,
  ActionCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ActionCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ActionCode_IsValid(int value);
constexpr ActionCode ActionCode_MIN = ActionNone;
constexpr ActionCode ActionCode_MAX = Login;
constexpr int ActionCode_ARRAYSIZE = ActionCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ActionCode_descriptor();
template<typename T>
inline const std::string& ActionCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ActionCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ActionCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ActionCode_descriptor(), enum_t_value);
}
inline bool ActionCode_Parse(
    const std::string& name, ActionCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ActionCode>(
    ActionCode_descriptor(), name, value);
}
enum ReturnCode : int {
  ReturnNone = 0,
  Succeed = 1,
  Fail = 2,
  ReturnCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ReturnCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ReturnCode_IsValid(int value);
constexpr ReturnCode ReturnCode_MIN = ReturnNone;
constexpr ReturnCode ReturnCode_MAX = Fail;
constexpr int ReturnCode_ARRAYSIZE = ReturnCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ReturnCode_descriptor();
template<typename T>
inline const std::string& ReturnCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ReturnCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ReturnCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ReturnCode_descriptor(), enum_t_value);
}
inline bool ReturnCode_Parse(
    const std::string& name, ReturnCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ReturnCode>(
    ReturnCode_descriptor(), name, value);
}
// ===================================================================

class AccountLoginReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AccountLoginReq) */ {
 public:
  inline AccountLoginReq() : AccountLoginReq(nullptr) {};
  virtual ~AccountLoginReq();

  AccountLoginReq(const AccountLoginReq& from);
  AccountLoginReq(AccountLoginReq&& from) noexcept
    : AccountLoginReq() {
    *this = ::std::move(from);
  }

  inline AccountLoginReq& operator=(const AccountLoginReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountLoginReq& operator=(AccountLoginReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AccountLoginReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AccountLoginReq* internal_default_instance() {
    return reinterpret_cast<const AccountLoginReq*>(
               &_AccountLoginReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AccountLoginReq& a, AccountLoginReq& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountLoginReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountLoginReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AccountLoginReq* New() const final {
    return CreateMaybeMessage<AccountLoginReq>(nullptr);
  }

  AccountLoginReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AccountLoginReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AccountLoginReq& from);
  void MergeFrom(const AccountLoginReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountLoginReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AccountLoginReq";
  }
  protected:
  explicit AccountLoginReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Login_2eproto);
    return ::descriptor_table_Login_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPasswordFieldNumber = 2,
    kAccountFieldNumber = 1,
  };
  // string password = 2;
  void clear_password();
  const std::string& password() const;
  void set_password(const std::string& value);
  void set_password(std::string&& value);
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  std::string* mutable_password();
  std::string* release_password();
  void set_allocated_password(std::string* password);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_password();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_password(
      std::string* password);
  private:
  const std::string& _internal_password() const;
  void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // uint64 account = 1;
  void clear_account();
  ::PROTOBUF_NAMESPACE_ID::uint64 account() const;
  void set_account(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_account() const;
  void _internal_set_account(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:AccountLoginReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  ::PROTOBUF_NAMESPACE_ID::uint64 account_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Login_2eproto;
};
// -------------------------------------------------------------------

class AccountLoginAck PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AccountLoginAck) */ {
 public:
  inline AccountLoginAck() : AccountLoginAck(nullptr) {};
  virtual ~AccountLoginAck();

  AccountLoginAck(const AccountLoginAck& from);
  AccountLoginAck(AccountLoginAck&& from) noexcept
    : AccountLoginAck() {
    *this = ::std::move(from);
  }

  inline AccountLoginAck& operator=(const AccountLoginAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountLoginAck& operator=(AccountLoginAck&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AccountLoginAck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AccountLoginAck* internal_default_instance() {
    return reinterpret_cast<const AccountLoginAck*>(
               &_AccountLoginAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AccountLoginAck& a, AccountLoginAck& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountLoginAck* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountLoginAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AccountLoginAck* New() const final {
    return CreateMaybeMessage<AccountLoginAck>(nullptr);
  }

  AccountLoginAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AccountLoginAck>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AccountLoginAck& from);
  void MergeFrom(const AccountLoginAck& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountLoginAck* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AccountLoginAck";
  }
  protected:
  explicit AccountLoginAck(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Login_2eproto);
    return ::descriptor_table_Login_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResFieldNumber = 1,
    kSockfdFieldNumber = 2,
  };
  // int32 res = 1;
  void clear_res();
  ::PROTOBUF_NAMESPACE_ID::int32 res() const;
  void set_res(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_res() const;
  void _internal_set_res(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 sockfd = 2;
  void clear_sockfd();
  ::PROTOBUF_NAMESPACE_ID::int32 sockfd() const;
  void set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_sockfd() const;
  void _internal_set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:AccountLoginAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 res_;
  ::PROTOBUF_NAMESPACE_ID::int32 sockfd_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Login_2eproto;
};
// -------------------------------------------------------------------

class AccountRegisterReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AccountRegisterReq) */ {
 public:
  inline AccountRegisterReq() : AccountRegisterReq(nullptr) {};
  virtual ~AccountRegisterReq();

  AccountRegisterReq(const AccountRegisterReq& from);
  AccountRegisterReq(AccountRegisterReq&& from) noexcept
    : AccountRegisterReq() {
    *this = ::std::move(from);
  }

  inline AccountRegisterReq& operator=(const AccountRegisterReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountRegisterReq& operator=(AccountRegisterReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AccountRegisterReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AccountRegisterReq* internal_default_instance() {
    return reinterpret_cast<const AccountRegisterReq*>(
               &_AccountRegisterReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AccountRegisterReq& a, AccountRegisterReq& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountRegisterReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountRegisterReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AccountRegisterReq* New() const final {
    return CreateMaybeMessage<AccountRegisterReq>(nullptr);
  }

  AccountRegisterReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AccountRegisterReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AccountRegisterReq& from);
  void MergeFrom(const AccountRegisterReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountRegisterReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AccountRegisterReq";
  }
  protected:
  explicit AccountRegisterReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Login_2eproto);
    return ::descriptor_table_Login_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPasswordFieldNumber = 2,
    kNameFieldNumber = 3,
    kAccountFieldNumber = 1,
  };
  // string password = 2;
  void clear_password();
  const std::string& password() const;
  void set_password(const std::string& value);
  void set_password(std::string&& value);
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  std::string* mutable_password();
  std::string* release_password();
  void set_allocated_password(std::string* password);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_password();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_password(
      std::string* password);
  private:
  const std::string& _internal_password() const;
  void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // string name = 3;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // uint64 account = 1;
  void clear_account();
  ::PROTOBUF_NAMESPACE_ID::uint64 account() const;
  void set_account(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_account() const;
  void _internal_set_account(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:AccountRegisterReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::uint64 account_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Login_2eproto;
};
// -------------------------------------------------------------------

class AccountRegisterAck PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:AccountRegisterAck) */ {
 public:
  inline AccountRegisterAck() : AccountRegisterAck(nullptr) {};
  virtual ~AccountRegisterAck();

  AccountRegisterAck(const AccountRegisterAck& from);
  AccountRegisterAck(AccountRegisterAck&& from) noexcept
    : AccountRegisterAck() {
    *this = ::std::move(from);
  }

  inline AccountRegisterAck& operator=(const AccountRegisterAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline AccountRegisterAck& operator=(AccountRegisterAck&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AccountRegisterAck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AccountRegisterAck* internal_default_instance() {
    return reinterpret_cast<const AccountRegisterAck*>(
               &_AccountRegisterAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(AccountRegisterAck& a, AccountRegisterAck& b) {
    a.Swap(&b);
  }
  inline void Swap(AccountRegisterAck* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AccountRegisterAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AccountRegisterAck* New() const final {
    return CreateMaybeMessage<AccountRegisterAck>(nullptr);
  }

  AccountRegisterAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AccountRegisterAck>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AccountRegisterAck& from);
  void MergeFrom(const AccountRegisterAck& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AccountRegisterAck* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "AccountRegisterAck";
  }
  protected:
  explicit AccountRegisterAck(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Login_2eproto);
    return ::descriptor_table_Login_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResFieldNumber = 1,
    kSockfdFieldNumber = 2,
  };
  // int32 res = 1;
  void clear_res();
  ::PROTOBUF_NAMESPACE_ID::int32 res() const;
  void set_res(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_res() const;
  void _internal_set_res(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 sockfd = 2;
  void clear_sockfd();
  ::PROTOBUF_NAMESPACE_ID::int32 sockfd() const;
  void set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_sockfd() const;
  void _internal_set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:AccountRegisterAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 res_;
  ::PROTOBUF_NAMESPACE_ID::int32 sockfd_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Login_2eproto;
};
// -------------------------------------------------------------------

class SelectEnterLogicSvrReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SelectEnterLogicSvrReq) */ {
 public:
  inline SelectEnterLogicSvrReq() : SelectEnterLogicSvrReq(nullptr) {};
  virtual ~SelectEnterLogicSvrReq();

  SelectEnterLogicSvrReq(const SelectEnterLogicSvrReq& from);
  SelectEnterLogicSvrReq(SelectEnterLogicSvrReq&& from) noexcept
    : SelectEnterLogicSvrReq() {
    *this = ::std::move(from);
  }

  inline SelectEnterLogicSvrReq& operator=(const SelectEnterLogicSvrReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline SelectEnterLogicSvrReq& operator=(SelectEnterLogicSvrReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SelectEnterLogicSvrReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SelectEnterLogicSvrReq* internal_default_instance() {
    return reinterpret_cast<const SelectEnterLogicSvrReq*>(
               &_SelectEnterLogicSvrReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(SelectEnterLogicSvrReq& a, SelectEnterLogicSvrReq& b) {
    a.Swap(&b);
  }
  inline void Swap(SelectEnterLogicSvrReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SelectEnterLogicSvrReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SelectEnterLogicSvrReq* New() const final {
    return CreateMaybeMessage<SelectEnterLogicSvrReq>(nullptr);
  }

  SelectEnterLogicSvrReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SelectEnterLogicSvrReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SelectEnterLogicSvrReq& from);
  void MergeFrom(const SelectEnterLogicSvrReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SelectEnterLogicSvrReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SelectEnterLogicSvrReq";
  }
  protected:
  explicit SelectEnterLogicSvrReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Login_2eproto);
    return ::descriptor_table_Login_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountFieldNumber = 1,
    kServeridFieldNumber = 2,
    kSockfdFieldNumber = 3,
  };
  // uint64 account = 1;
  void clear_account();
  ::PROTOBUF_NAMESPACE_ID::uint64 account() const;
  void set_account(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_account() const;
  void _internal_set_account(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // int32 serverid = 2;
  void clear_serverid();
  ::PROTOBUF_NAMESPACE_ID::int32 serverid() const;
  void set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_serverid() const;
  void _internal_set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 sockfd = 3;
  void clear_sockfd();
  ::PROTOBUF_NAMESPACE_ID::int32 sockfd() const;
  void set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_sockfd() const;
  void _internal_set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:SelectEnterLogicSvrReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 account_;
  ::PROTOBUF_NAMESPACE_ID::int32 serverid_;
  ::PROTOBUF_NAMESPACE_ID::int32 sockfd_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Login_2eproto;
};
// -------------------------------------------------------------------

class SelectEnterLogicSvrAck PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SelectEnterLogicSvrAck) */ {
 public:
  inline SelectEnterLogicSvrAck() : SelectEnterLogicSvrAck(nullptr) {};
  virtual ~SelectEnterLogicSvrAck();

  SelectEnterLogicSvrAck(const SelectEnterLogicSvrAck& from);
  SelectEnterLogicSvrAck(SelectEnterLogicSvrAck&& from) noexcept
    : SelectEnterLogicSvrAck() {
    *this = ::std::move(from);
  }

  inline SelectEnterLogicSvrAck& operator=(const SelectEnterLogicSvrAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline SelectEnterLogicSvrAck& operator=(SelectEnterLogicSvrAck&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SelectEnterLogicSvrAck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SelectEnterLogicSvrAck* internal_default_instance() {
    return reinterpret_cast<const SelectEnterLogicSvrAck*>(
               &_SelectEnterLogicSvrAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(SelectEnterLogicSvrAck& a, SelectEnterLogicSvrAck& b) {
    a.Swap(&b);
  }
  inline void Swap(SelectEnterLogicSvrAck* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SelectEnterLogicSvrAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SelectEnterLogicSvrAck* New() const final {
    return CreateMaybeMessage<SelectEnterLogicSvrAck>(nullptr);
  }

  SelectEnterLogicSvrAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SelectEnterLogicSvrAck>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SelectEnterLogicSvrAck& from);
  void MergeFrom(const SelectEnterLogicSvrAck& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SelectEnterLogicSvrAck* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SelectEnterLogicSvrAck";
  }
  protected:
  explicit SelectEnterLogicSvrAck(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Login_2eproto);
    return ::descriptor_table_Login_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServeraddrFieldNumber = 3,
    kAccountFieldNumber = 1,
    kServeridFieldNumber = 2,
    kServerportFieldNumber = 4,
    kLogincodeFieldNumber = 5,
    kSockfdFieldNumber = 6,
  };
  // string serveraddr = 3;
  void clear_serveraddr();
  const std::string& serveraddr() const;
  void set_serveraddr(const std::string& value);
  void set_serveraddr(std::string&& value);
  void set_serveraddr(const char* value);
  void set_serveraddr(const char* value, size_t size);
  std::string* mutable_serveraddr();
  std::string* release_serveraddr();
  void set_allocated_serveraddr(std::string* serveraddr);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_serveraddr();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_serveraddr(
      std::string* serveraddr);
  private:
  const std::string& _internal_serveraddr() const;
  void _internal_set_serveraddr(const std::string& value);
  std::string* _internal_mutable_serveraddr();
  public:

  // uint64 account = 1;
  void clear_account();
  ::PROTOBUF_NAMESPACE_ID::uint64 account() const;
  void set_account(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_account() const;
  void _internal_set_account(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // int32 serverid = 2;
  void clear_serverid();
  ::PROTOBUF_NAMESPACE_ID::int32 serverid() const;
  void set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_serverid() const;
  void _internal_set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 serverport = 4;
  void clear_serverport();
  ::PROTOBUF_NAMESPACE_ID::int32 serverport() const;
  void set_serverport(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_serverport() const;
  void _internal_set_serverport(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 logincode = 5;
  void clear_logincode();
  ::PROTOBUF_NAMESPACE_ID::int32 logincode() const;
  void set_logincode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_logincode() const;
  void _internal_set_logincode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 sockfd = 6;
  void clear_sockfd();
  ::PROTOBUF_NAMESPACE_ID::int32 sockfd() const;
  void set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_sockfd() const;
  void _internal_set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:SelectEnterLogicSvrAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr serveraddr_;
  ::PROTOBUF_NAMESPACE_ID::uint64 account_;
  ::PROTOBUF_NAMESPACE_ID::int32 serverid_;
  ::PROTOBUF_NAMESPACE_ID::int32 serverport_;
  ::PROTOBUF_NAMESPACE_ID::int32 logincode_;
  ::PROTOBUF_NAMESPACE_ID::int32 sockfd_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Login_2eproto;
};
// -------------------------------------------------------------------

class LoadLogicSvrReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LoadLogicSvrReq) */ {
 public:
  inline LoadLogicSvrReq() : LoadLogicSvrReq(nullptr) {};
  virtual ~LoadLogicSvrReq();

  LoadLogicSvrReq(const LoadLogicSvrReq& from);
  LoadLogicSvrReq(LoadLogicSvrReq&& from) noexcept
    : LoadLogicSvrReq() {
    *this = ::std::move(from);
  }

  inline LoadLogicSvrReq& operator=(const LoadLogicSvrReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoadLogicSvrReq& operator=(LoadLogicSvrReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LoadLogicSvrReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoadLogicSvrReq* internal_default_instance() {
    return reinterpret_cast<const LoadLogicSvrReq*>(
               &_LoadLogicSvrReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(LoadLogicSvrReq& a, LoadLogicSvrReq& b) {
    a.Swap(&b);
  }
  inline void Swap(LoadLogicSvrReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoadLogicSvrReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LoadLogicSvrReq* New() const final {
    return CreateMaybeMessage<LoadLogicSvrReq>(nullptr);
  }

  LoadLogicSvrReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LoadLogicSvrReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LoadLogicSvrReq& from);
  void MergeFrom(const LoadLogicSvrReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LoadLogicSvrReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LoadLogicSvrReq";
  }
  protected:
  explicit LoadLogicSvrReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Login_2eproto);
    return ::descriptor_table_Login_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:LoadLogicSvrReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Login_2eproto;
};
// -------------------------------------------------------------------

class MainPack PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MainPack) */ {
 public:
  inline MainPack() : MainPack(nullptr) {};
  virtual ~MainPack();

  MainPack(const MainPack& from);
  MainPack(MainPack&& from) noexcept
    : MainPack() {
    *this = ::std::move(from);
  }

  inline MainPack& operator=(const MainPack& from) {
    CopyFrom(from);
    return *this;
  }
  inline MainPack& operator=(MainPack&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MainPack& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MainPack* internal_default_instance() {
    return reinterpret_cast<const MainPack*>(
               &_MainPack_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(MainPack& a, MainPack& b) {
    a.Swap(&b);
  }
  inline void Swap(MainPack* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MainPack* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MainPack* New() const final {
    return CreateMaybeMessage<MainPack>(nullptr);
  }

  MainPack* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MainPack>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MainPack& from);
  void MergeFrom(const MainPack& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MainPack* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MainPack";
  }
  protected:
  explicit MainPack(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Login_2eproto);
    return ::descriptor_table_Login_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLogonpackFieldNumber = 4,
    kRequestcodeFieldNumber = 1,
    kActioncodeFieldNumber = 2,
    kReturncodeFieldNumber = 3,
  };
  // .LogonPack logonpack = 4;
  bool has_logonpack() const;
  private:
  bool _internal_has_logonpack() const;
  public:
  void clear_logonpack();
  const ::LogonPack& logonpack() const;
  ::LogonPack* release_logonpack();
  ::LogonPack* mutable_logonpack();
  void set_allocated_logonpack(::LogonPack* logonpack);
  private:
  const ::LogonPack& _internal_logonpack() const;
  ::LogonPack* _internal_mutable_logonpack();
  public:
  void unsafe_arena_set_allocated_logonpack(
      ::LogonPack* logonpack);
  ::LogonPack* unsafe_arena_release_logonpack();

  // .RequestCode requestcode = 1;
  void clear_requestcode();
  ::RequestCode requestcode() const;
  void set_requestcode(::RequestCode value);
  private:
  ::RequestCode _internal_requestcode() const;
  void _internal_set_requestcode(::RequestCode value);
  public:

  // .ActionCode actioncode = 2;
  void clear_actioncode();
  ::ActionCode actioncode() const;
  void set_actioncode(::ActionCode value);
  private:
  ::ActionCode _internal_actioncode() const;
  void _internal_set_actioncode(::ActionCode value);
  public:

  // .ReturnCode returncode = 3;
  void clear_returncode();
  ::ReturnCode returncode() const;
  void set_returncode(::ReturnCode value);
  private:
  ::ReturnCode _internal_returncode() const;
  void _internal_set_returncode(::ReturnCode value);
  public:

  // @@protoc_insertion_point(class_scope:MainPack)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::LogonPack* logonpack_;
  int requestcode_;
  int actioncode_;
  int returncode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Login_2eproto;
};
// -------------------------------------------------------------------

class LogonPack PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LogonPack) */ {
 public:
  inline LogonPack() : LogonPack(nullptr) {};
  virtual ~LogonPack();

  LogonPack(const LogonPack& from);
  LogonPack(LogonPack&& from) noexcept
    : LogonPack() {
    *this = ::std::move(from);
  }

  inline LogonPack& operator=(const LogonPack& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogonPack& operator=(LogonPack&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LogonPack& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogonPack* internal_default_instance() {
    return reinterpret_cast<const LogonPack*>(
               &_LogonPack_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(LogonPack& a, LogonPack& b) {
    a.Swap(&b);
  }
  inline void Swap(LogonPack* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogonPack* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LogonPack* New() const final {
    return CreateMaybeMessage<LogonPack>(nullptr);
  }

  LogonPack* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LogonPack>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LogonPack& from);
  void MergeFrom(const LogonPack& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogonPack* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LogonPack";
  }
  protected:
  explicit LogonPack(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Login_2eproto);
    return ::descriptor_table_Login_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsernameFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // string username = 1;
  void clear_username();
  const std::string& username() const;
  void set_username(const std::string& value);
  void set_username(std::string&& value);
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  std::string* mutable_username();
  std::string* release_username();
  void set_allocated_username(std::string* username);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_username();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_username(
      std::string* username);
  private:
  const std::string& _internal_username() const;
  void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // string password = 2;
  void clear_password();
  const std::string& password() const;
  void set_password(const std::string& value);
  void set_password(std::string&& value);
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  std::string* mutable_password();
  std::string* release_password();
  void set_allocated_password(std::string* password);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_password();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_password(
      std::string* password);
  private:
  const std::string& _internal_password() const;
  void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // @@protoc_insertion_point(class_scope:LogonPack)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Login_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AccountLoginReq

// uint64 account = 1;
inline void AccountLoginReq::clear_account() {
  account_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AccountLoginReq::_internal_account() const {
  return account_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AccountLoginReq::account() const {
  // @@protoc_insertion_point(field_get:AccountLoginReq.account)
  return _internal_account();
}
inline void AccountLoginReq::_internal_set_account(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  account_ = value;
}
inline void AccountLoginReq::set_account(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_account(value);
  // @@protoc_insertion_point(field_set:AccountLoginReq.account)
}

// string password = 2;
inline void AccountLoginReq::clear_password() {
  password_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& AccountLoginReq::password() const {
  // @@protoc_insertion_point(field_get:AccountLoginReq.password)
  return _internal_password();
}
inline void AccountLoginReq::set_password(const std::string& value) {
  _internal_set_password(value);
  // @@protoc_insertion_point(field_set:AccountLoginReq.password)
}
inline std::string* AccountLoginReq::mutable_password() {
  // @@protoc_insertion_point(field_mutable:AccountLoginReq.password)
  return _internal_mutable_password();
}
inline const std::string& AccountLoginReq::_internal_password() const {
  return password_.Get();
}
inline void AccountLoginReq::_internal_set_password(const std::string& value) {
  
  password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void AccountLoginReq::set_password(std::string&& value) {
  
  password_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:AccountLoginReq.password)
}
inline void AccountLoginReq::set_password(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:AccountLoginReq.password)
}
inline void AccountLoginReq::set_password(const char* value,
    size_t size) {
  
  password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:AccountLoginReq.password)
}
inline std::string* AccountLoginReq::_internal_mutable_password() {
  
  return password_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* AccountLoginReq::release_password() {
  // @@protoc_insertion_point(field_release:AccountLoginReq.password)
  return password_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AccountLoginReq::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:AccountLoginReq.password)
}
inline std::string* AccountLoginReq::unsafe_arena_release_password() {
  // @@protoc_insertion_point(field_unsafe_arena_release:AccountLoginReq.password)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return password_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void AccountLoginReq::unsafe_arena_set_allocated_password(
    std::string* password) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (password != nullptr) {
    
  } else {
    
  }
  password_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      password, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AccountLoginReq.password)
}

// -------------------------------------------------------------------

// AccountLoginAck

// int32 res = 1;
inline void AccountLoginAck::clear_res() {
  res_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 AccountLoginAck::_internal_res() const {
  return res_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 AccountLoginAck::res() const {
  // @@protoc_insertion_point(field_get:AccountLoginAck.res)
  return _internal_res();
}
inline void AccountLoginAck::_internal_set_res(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  res_ = value;
}
inline void AccountLoginAck::set_res(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_res(value);
  // @@protoc_insertion_point(field_set:AccountLoginAck.res)
}

// int32 sockfd = 2;
inline void AccountLoginAck::clear_sockfd() {
  sockfd_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 AccountLoginAck::_internal_sockfd() const {
  return sockfd_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 AccountLoginAck::sockfd() const {
  // @@protoc_insertion_point(field_get:AccountLoginAck.sockfd)
  return _internal_sockfd();
}
inline void AccountLoginAck::_internal_set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sockfd_ = value;
}
inline void AccountLoginAck::set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_sockfd(value);
  // @@protoc_insertion_point(field_set:AccountLoginAck.sockfd)
}

// -------------------------------------------------------------------

// AccountRegisterReq

// uint64 account = 1;
inline void AccountRegisterReq::clear_account() {
  account_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AccountRegisterReq::_internal_account() const {
  return account_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AccountRegisterReq::account() const {
  // @@protoc_insertion_point(field_get:AccountRegisterReq.account)
  return _internal_account();
}
inline void AccountRegisterReq::_internal_set_account(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  account_ = value;
}
inline void AccountRegisterReq::set_account(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_account(value);
  // @@protoc_insertion_point(field_set:AccountRegisterReq.account)
}

// string password = 2;
inline void AccountRegisterReq::clear_password() {
  password_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& AccountRegisterReq::password() const {
  // @@protoc_insertion_point(field_get:AccountRegisterReq.password)
  return _internal_password();
}
inline void AccountRegisterReq::set_password(const std::string& value) {
  _internal_set_password(value);
  // @@protoc_insertion_point(field_set:AccountRegisterReq.password)
}
inline std::string* AccountRegisterReq::mutable_password() {
  // @@protoc_insertion_point(field_mutable:AccountRegisterReq.password)
  return _internal_mutable_password();
}
inline const std::string& AccountRegisterReq::_internal_password() const {
  return password_.Get();
}
inline void AccountRegisterReq::_internal_set_password(const std::string& value) {
  
  password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void AccountRegisterReq::set_password(std::string&& value) {
  
  password_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:AccountRegisterReq.password)
}
inline void AccountRegisterReq::set_password(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:AccountRegisterReq.password)
}
inline void AccountRegisterReq::set_password(const char* value,
    size_t size) {
  
  password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:AccountRegisterReq.password)
}
inline std::string* AccountRegisterReq::_internal_mutable_password() {
  
  return password_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* AccountRegisterReq::release_password() {
  // @@protoc_insertion_point(field_release:AccountRegisterReq.password)
  return password_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AccountRegisterReq::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:AccountRegisterReq.password)
}
inline std::string* AccountRegisterReq::unsafe_arena_release_password() {
  // @@protoc_insertion_point(field_unsafe_arena_release:AccountRegisterReq.password)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return password_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void AccountRegisterReq::unsafe_arena_set_allocated_password(
    std::string* password) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (password != nullptr) {
    
  } else {
    
  }
  password_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      password, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AccountRegisterReq.password)
}

// string name = 3;
inline void AccountRegisterReq::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& AccountRegisterReq::name() const {
  // @@protoc_insertion_point(field_get:AccountRegisterReq.name)
  return _internal_name();
}
inline void AccountRegisterReq::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:AccountRegisterReq.name)
}
inline std::string* AccountRegisterReq::mutable_name() {
  // @@protoc_insertion_point(field_mutable:AccountRegisterReq.name)
  return _internal_mutable_name();
}
inline const std::string& AccountRegisterReq::_internal_name() const {
  return name_.Get();
}
inline void AccountRegisterReq::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void AccountRegisterReq::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:AccountRegisterReq.name)
}
inline void AccountRegisterReq::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:AccountRegisterReq.name)
}
inline void AccountRegisterReq::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:AccountRegisterReq.name)
}
inline std::string* AccountRegisterReq::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* AccountRegisterReq::release_name() {
  // @@protoc_insertion_point(field_release:AccountRegisterReq.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AccountRegisterReq::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:AccountRegisterReq.name)
}
inline std::string* AccountRegisterReq::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:AccountRegisterReq.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void AccountRegisterReq::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AccountRegisterReq.name)
}

// -------------------------------------------------------------------

// AccountRegisterAck

// int32 res = 1;
inline void AccountRegisterAck::clear_res() {
  res_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 AccountRegisterAck::_internal_res() const {
  return res_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 AccountRegisterAck::res() const {
  // @@protoc_insertion_point(field_get:AccountRegisterAck.res)
  return _internal_res();
}
inline void AccountRegisterAck::_internal_set_res(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  res_ = value;
}
inline void AccountRegisterAck::set_res(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_res(value);
  // @@protoc_insertion_point(field_set:AccountRegisterAck.res)
}

// int32 sockfd = 2;
inline void AccountRegisterAck::clear_sockfd() {
  sockfd_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 AccountRegisterAck::_internal_sockfd() const {
  return sockfd_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 AccountRegisterAck::sockfd() const {
  // @@protoc_insertion_point(field_get:AccountRegisterAck.sockfd)
  return _internal_sockfd();
}
inline void AccountRegisterAck::_internal_set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sockfd_ = value;
}
inline void AccountRegisterAck::set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_sockfd(value);
  // @@protoc_insertion_point(field_set:AccountRegisterAck.sockfd)
}

// -------------------------------------------------------------------

// SelectEnterLogicSvrReq

// uint64 account = 1;
inline void SelectEnterLogicSvrReq::clear_account() {
  account_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SelectEnterLogicSvrReq::_internal_account() const {
  return account_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SelectEnterLogicSvrReq::account() const {
  // @@protoc_insertion_point(field_get:SelectEnterLogicSvrReq.account)
  return _internal_account();
}
inline void SelectEnterLogicSvrReq::_internal_set_account(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  account_ = value;
}
inline void SelectEnterLogicSvrReq::set_account(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_account(value);
  // @@protoc_insertion_point(field_set:SelectEnterLogicSvrReq.account)
}

// int32 serverid = 2;
inline void SelectEnterLogicSvrReq::clear_serverid() {
  serverid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SelectEnterLogicSvrReq::_internal_serverid() const {
  return serverid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SelectEnterLogicSvrReq::serverid() const {
  // @@protoc_insertion_point(field_get:SelectEnterLogicSvrReq.serverid)
  return _internal_serverid();
}
inline void SelectEnterLogicSvrReq::_internal_set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  serverid_ = value;
}
inline void SelectEnterLogicSvrReq::set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_serverid(value);
  // @@protoc_insertion_point(field_set:SelectEnterLogicSvrReq.serverid)
}

// int32 sockfd = 3;
inline void SelectEnterLogicSvrReq::clear_sockfd() {
  sockfd_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SelectEnterLogicSvrReq::_internal_sockfd() const {
  return sockfd_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SelectEnterLogicSvrReq::sockfd() const {
  // @@protoc_insertion_point(field_get:SelectEnterLogicSvrReq.sockfd)
  return _internal_sockfd();
}
inline void SelectEnterLogicSvrReq::_internal_set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sockfd_ = value;
}
inline void SelectEnterLogicSvrReq::set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_sockfd(value);
  // @@protoc_insertion_point(field_set:SelectEnterLogicSvrReq.sockfd)
}

// -------------------------------------------------------------------

// SelectEnterLogicSvrAck

// uint64 account = 1;
inline void SelectEnterLogicSvrAck::clear_account() {
  account_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SelectEnterLogicSvrAck::_internal_account() const {
  return account_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SelectEnterLogicSvrAck::account() const {
  // @@protoc_insertion_point(field_get:SelectEnterLogicSvrAck.account)
  return _internal_account();
}
inline void SelectEnterLogicSvrAck::_internal_set_account(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  account_ = value;
}
inline void SelectEnterLogicSvrAck::set_account(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_account(value);
  // @@protoc_insertion_point(field_set:SelectEnterLogicSvrAck.account)
}

// int32 serverid = 2;
inline void SelectEnterLogicSvrAck::clear_serverid() {
  serverid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SelectEnterLogicSvrAck::_internal_serverid() const {
  return serverid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SelectEnterLogicSvrAck::serverid() const {
  // @@protoc_insertion_point(field_get:SelectEnterLogicSvrAck.serverid)
  return _internal_serverid();
}
inline void SelectEnterLogicSvrAck::_internal_set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  serverid_ = value;
}
inline void SelectEnterLogicSvrAck::set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_serverid(value);
  // @@protoc_insertion_point(field_set:SelectEnterLogicSvrAck.serverid)
}

// string serveraddr = 3;
inline void SelectEnterLogicSvrAck::clear_serveraddr() {
  serveraddr_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& SelectEnterLogicSvrAck::serveraddr() const {
  // @@protoc_insertion_point(field_get:SelectEnterLogicSvrAck.serveraddr)
  return _internal_serveraddr();
}
inline void SelectEnterLogicSvrAck::set_serveraddr(const std::string& value) {
  _internal_set_serveraddr(value);
  // @@protoc_insertion_point(field_set:SelectEnterLogicSvrAck.serveraddr)
}
inline std::string* SelectEnterLogicSvrAck::mutable_serveraddr() {
  // @@protoc_insertion_point(field_mutable:SelectEnterLogicSvrAck.serveraddr)
  return _internal_mutable_serveraddr();
}
inline const std::string& SelectEnterLogicSvrAck::_internal_serveraddr() const {
  return serveraddr_.Get();
}
inline void SelectEnterLogicSvrAck::_internal_set_serveraddr(const std::string& value) {
  
  serveraddr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void SelectEnterLogicSvrAck::set_serveraddr(std::string&& value) {
  
  serveraddr_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:SelectEnterLogicSvrAck.serveraddr)
}
inline void SelectEnterLogicSvrAck::set_serveraddr(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  serveraddr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:SelectEnterLogicSvrAck.serveraddr)
}
inline void SelectEnterLogicSvrAck::set_serveraddr(const char* value,
    size_t size) {
  
  serveraddr_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:SelectEnterLogicSvrAck.serveraddr)
}
inline std::string* SelectEnterLogicSvrAck::_internal_mutable_serveraddr() {
  
  return serveraddr_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* SelectEnterLogicSvrAck::release_serveraddr() {
  // @@protoc_insertion_point(field_release:SelectEnterLogicSvrAck.serveraddr)
  return serveraddr_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SelectEnterLogicSvrAck::set_allocated_serveraddr(std::string* serveraddr) {
  if (serveraddr != nullptr) {
    
  } else {
    
  }
  serveraddr_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), serveraddr,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:SelectEnterLogicSvrAck.serveraddr)
}
inline std::string* SelectEnterLogicSvrAck::unsafe_arena_release_serveraddr() {
  // @@protoc_insertion_point(field_unsafe_arena_release:SelectEnterLogicSvrAck.serveraddr)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return serveraddr_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void SelectEnterLogicSvrAck::unsafe_arena_set_allocated_serveraddr(
    std::string* serveraddr) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (serveraddr != nullptr) {
    
  } else {
    
  }
  serveraddr_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      serveraddr, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:SelectEnterLogicSvrAck.serveraddr)
}

// int32 serverport = 4;
inline void SelectEnterLogicSvrAck::clear_serverport() {
  serverport_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SelectEnterLogicSvrAck::_internal_serverport() const {
  return serverport_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SelectEnterLogicSvrAck::serverport() const {
  // @@protoc_insertion_point(field_get:SelectEnterLogicSvrAck.serverport)
  return _internal_serverport();
}
inline void SelectEnterLogicSvrAck::_internal_set_serverport(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  serverport_ = value;
}
inline void SelectEnterLogicSvrAck::set_serverport(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_serverport(value);
  // @@protoc_insertion_point(field_set:SelectEnterLogicSvrAck.serverport)
}

// int32 logincode = 5;
inline void SelectEnterLogicSvrAck::clear_logincode() {
  logincode_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SelectEnterLogicSvrAck::_internal_logincode() const {
  return logincode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SelectEnterLogicSvrAck::logincode() const {
  // @@protoc_insertion_point(field_get:SelectEnterLogicSvrAck.logincode)
  return _internal_logincode();
}
inline void SelectEnterLogicSvrAck::_internal_set_logincode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  logincode_ = value;
}
inline void SelectEnterLogicSvrAck::set_logincode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_logincode(value);
  // @@protoc_insertion_point(field_set:SelectEnterLogicSvrAck.logincode)
}

// int32 sockfd = 6;
inline void SelectEnterLogicSvrAck::clear_sockfd() {
  sockfd_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SelectEnterLogicSvrAck::_internal_sockfd() const {
  return sockfd_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SelectEnterLogicSvrAck::sockfd() const {
  // @@protoc_insertion_point(field_get:SelectEnterLogicSvrAck.sockfd)
  return _internal_sockfd();
}
inline void SelectEnterLogicSvrAck::_internal_set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sockfd_ = value;
}
inline void SelectEnterLogicSvrAck::set_sockfd(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_sockfd(value);
  // @@protoc_insertion_point(field_set:SelectEnterLogicSvrAck.sockfd)
}

// -------------------------------------------------------------------

// LoadLogicSvrReq

// -------------------------------------------------------------------

// MainPack

// .RequestCode requestcode = 1;
inline void MainPack::clear_requestcode() {
  requestcode_ = 0;
}
inline ::RequestCode MainPack::_internal_requestcode() const {
  return static_cast< ::RequestCode >(requestcode_);
}
inline ::RequestCode MainPack::requestcode() const {
  // @@protoc_insertion_point(field_get:MainPack.requestcode)
  return _internal_requestcode();
}
inline void MainPack::_internal_set_requestcode(::RequestCode value) {
  
  requestcode_ = value;
}
inline void MainPack::set_requestcode(::RequestCode value) {
  _internal_set_requestcode(value);
  // @@protoc_insertion_point(field_set:MainPack.requestcode)
}

// .ActionCode actioncode = 2;
inline void MainPack::clear_actioncode() {
  actioncode_ = 0;
}
inline ::ActionCode MainPack::_internal_actioncode() const {
  return static_cast< ::ActionCode >(actioncode_);
}
inline ::ActionCode MainPack::actioncode() const {
  // @@protoc_insertion_point(field_get:MainPack.actioncode)
  return _internal_actioncode();
}
inline void MainPack::_internal_set_actioncode(::ActionCode value) {
  
  actioncode_ = value;
}
inline void MainPack::set_actioncode(::ActionCode value) {
  _internal_set_actioncode(value);
  // @@protoc_insertion_point(field_set:MainPack.actioncode)
}

// .ReturnCode returncode = 3;
inline void MainPack::clear_returncode() {
  returncode_ = 0;
}
inline ::ReturnCode MainPack::_internal_returncode() const {
  return static_cast< ::ReturnCode >(returncode_);
}
inline ::ReturnCode MainPack::returncode() const {
  // @@protoc_insertion_point(field_get:MainPack.returncode)
  return _internal_returncode();
}
inline void MainPack::_internal_set_returncode(::ReturnCode value) {
  
  returncode_ = value;
}
inline void MainPack::set_returncode(::ReturnCode value) {
  _internal_set_returncode(value);
  // @@protoc_insertion_point(field_set:MainPack.returncode)
}

// .LogonPack logonpack = 4;
inline bool MainPack::_internal_has_logonpack() const {
  return this != internal_default_instance() && logonpack_ != nullptr;
}
inline bool MainPack::has_logonpack() const {
  return _internal_has_logonpack();
}
inline void MainPack::clear_logonpack() {
  if (GetArena() == nullptr && logonpack_ != nullptr) {
    delete logonpack_;
  }
  logonpack_ = nullptr;
}
inline const ::LogonPack& MainPack::_internal_logonpack() const {
  const ::LogonPack* p = logonpack_;
  return p != nullptr ? *p : *reinterpret_cast<const ::LogonPack*>(
      &::_LogonPack_default_instance_);
}
inline const ::LogonPack& MainPack::logonpack() const {
  // @@protoc_insertion_point(field_get:MainPack.logonpack)
  return _internal_logonpack();
}
inline void MainPack::unsafe_arena_set_allocated_logonpack(
    ::LogonPack* logonpack) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(logonpack_);
  }
  logonpack_ = logonpack;
  if (logonpack) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MainPack.logonpack)
}
inline ::LogonPack* MainPack::release_logonpack() {
  auto temp = unsafe_arena_release_logonpack();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::LogonPack* MainPack::unsafe_arena_release_logonpack() {
  // @@protoc_insertion_point(field_release:MainPack.logonpack)
  
  ::LogonPack* temp = logonpack_;
  logonpack_ = nullptr;
  return temp;
}
inline ::LogonPack* MainPack::_internal_mutable_logonpack() {
  
  if (logonpack_ == nullptr) {
    auto* p = CreateMaybeMessage<::LogonPack>(GetArena());
    logonpack_ = p;
  }
  return logonpack_;
}
inline ::LogonPack* MainPack::mutable_logonpack() {
  // @@protoc_insertion_point(field_mutable:MainPack.logonpack)
  return _internal_mutable_logonpack();
}
inline void MainPack::set_allocated_logonpack(::LogonPack* logonpack) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete logonpack_;
  }
  if (logonpack) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(logonpack);
    if (message_arena != submessage_arena) {
      logonpack = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, logonpack, submessage_arena);
    }
    
  } else {
    
  }
  logonpack_ = logonpack;
  // @@protoc_insertion_point(field_set_allocated:MainPack.logonpack)
}

// -------------------------------------------------------------------

// LogonPack

// string username = 1;
inline void LogonPack::clear_username() {
  username_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& LogonPack::username() const {
  // @@protoc_insertion_point(field_get:LogonPack.username)
  return _internal_username();
}
inline void LogonPack::set_username(const std::string& value) {
  _internal_set_username(value);
  // @@protoc_insertion_point(field_set:LogonPack.username)
}
inline std::string* LogonPack::mutable_username() {
  // @@protoc_insertion_point(field_mutable:LogonPack.username)
  return _internal_mutable_username();
}
inline const std::string& LogonPack::_internal_username() const {
  return username_.Get();
}
inline void LogonPack::_internal_set_username(const std::string& value) {
  
  username_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LogonPack::set_username(std::string&& value) {
  
  username_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:LogonPack.username)
}
inline void LogonPack::set_username(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  username_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:LogonPack.username)
}
inline void LogonPack::set_username(const char* value,
    size_t size) {
  
  username_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:LogonPack.username)
}
inline std::string* LogonPack::_internal_mutable_username() {
  
  return username_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LogonPack::release_username() {
  // @@protoc_insertion_point(field_release:LogonPack.username)
  return username_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogonPack::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  username_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), username,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:LogonPack.username)
}
inline std::string* LogonPack::unsafe_arena_release_username() {
  // @@protoc_insertion_point(field_unsafe_arena_release:LogonPack.username)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return username_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void LogonPack::unsafe_arena_set_allocated_username(
    std::string* username) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (username != nullptr) {
    
  } else {
    
  }
  username_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      username, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:LogonPack.username)
}

// string password = 2;
inline void LogonPack::clear_password() {
  password_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& LogonPack::password() const {
  // @@protoc_insertion_point(field_get:LogonPack.password)
  return _internal_password();
}
inline void LogonPack::set_password(const std::string& value) {
  _internal_set_password(value);
  // @@protoc_insertion_point(field_set:LogonPack.password)
}
inline std::string* LogonPack::mutable_password() {
  // @@protoc_insertion_point(field_mutable:LogonPack.password)
  return _internal_mutable_password();
}
inline const std::string& LogonPack::_internal_password() const {
  return password_.Get();
}
inline void LogonPack::_internal_set_password(const std::string& value) {
  
  password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void LogonPack::set_password(std::string&& value) {
  
  password_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:LogonPack.password)
}
inline void LogonPack::set_password(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:LogonPack.password)
}
inline void LogonPack::set_password(const char* value,
    size_t size) {
  
  password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:LogonPack.password)
}
inline std::string* LogonPack::_internal_mutable_password() {
  
  return password_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* LogonPack::release_password() {
  // @@protoc_insertion_point(field_release:LogonPack.password)
  return password_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogonPack::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    
  } else {
    
  }
  password_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:LogonPack.password)
}
inline std::string* LogonPack::unsafe_arena_release_password() {
  // @@protoc_insertion_point(field_unsafe_arena_release:LogonPack.password)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return password_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void LogonPack::unsafe_arena_set_allocated_password(
    std::string* password) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (password != nullptr) {
    
  } else {
    
  }
  password_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      password, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:LogonPack.password)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::RequestCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RequestCode>() {
  return ::RequestCode_descriptor();
}
template <> struct is_proto_enum< ::ActionCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ActionCode>() {
  return ::ActionCode_descriptor();
}
template <> struct is_proto_enum< ::ReturnCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ReturnCode>() {
  return ::ReturnCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Login_2eproto
